name: Build and Deploy Server to k8s

# This action works with pull requests and pushes
on:
  release:
    types: [published]

env:
  IMAGE_NAME: registry.digitalocean.com/nsgcr/artist-colony-orders-api
  CLUSTER_NAME: k8s-1-33-1-do-3-fra1-1757785023859
  K8S_NAMESPACE: nsg-artist-colony-orders

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Install doctl
        uses: digitalocean/action-doctl@135ac0aa0eed4437d547c6f12c364d3006b42824 # v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
           version: v1.33.5

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: DOKS Auth
        run: |
          doctl kubernetes cluster kubeconfig save $CLUSTER_NAME

      - name: Build & Push Image
        run: docker buildx build -t $IMAGE_NAME:${{ github.ref_name }} --push .

      # - name: Update deployment image tag
      #   run: |
      #     kubectl -n $K8S_NAMESPACE set image \
      #       deployment/artist-colony-orders-api \
      #       artist-colony-orders-api=$IMAGE_NAME:${{ github.ref_name }}
